### ISSUE TITLE
How can I read resource file in scala worksheet?

### ISSUE THREAD

**Issue by SongKJ00** [dev-andrey/advent-of-code#1]
**Thank you for your great scala code!**

I have some questions.

Your scala worksheet code looks like read resource file from project_root/src/main/resources.

But in my intellij, I can't read resource file in scala worksheet.

My project tree is as below.
![image](https://user-images.githubusercontent.com/23634620/105376150-c8bc8500-5c4c-11eb-880a-49afcc7d4e69.png)

And this is my worksheet code.
![image](https://user-images.githubusercontent.com/23634620/105376263-e7228080-5c4c-11eb-8915-32c07798c1c0.png)

Are there any settings that I have to do??

**Comment by dev-andrey** [comment]
@SongKJ00 thanks, I forgot to mention in README.md, you need to build it once.
alternatively you can configure worksheets to build before run
<img width="617" alt="image" src="https://user-images.githubusercontent.com/5165852/105379446-d46f6380-5bda-11eb-8164-036a4fcc0ba5.png">

**Comment by SongKJ00** [comment]
Sorry for late reply.

The problem was solved thanks to your kind answer! 

![image](https://user-images.githubusercontent.com/23634620/109918895-1839aa80-7cfb-11eb-9763-9c3d39ff5b7d.png)

Thank you! :+1:
